# Generated by Django 3.2.5 on 2021-07-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre de la categoria'),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='update',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de actualizacion'),
        ),
        migrations.AlterField(
            model_name='empresascliente',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='empresascliente',
            name='empresa',
            field=models.CharField(max_length=50, verbose_name='Nombrre de la empresa'),
        ),
        migrations.AlterField(
            model_name='empresascliente',
            name='update',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de actualizacion'),
        ),
    ]
