# Generated by Django 3.2.5 on 2021-07-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0002_auto_20210713_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='empresascliente',
            options={'verbose_name': 'Empresa cliente', 'verbose_name_plural': 'empresas clientes'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
