# Generated by Django 3.2.5 on 2021-07-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0003_auto_20210713_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='contenido',
            field=models.TextField(max_length=1000, verbose_name='Descripcion del protyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Portafolio', verbose_name='Imagen para mostrar'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Nombre del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='update',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de actualizacion'),
        ),
    ]
