# Generated by Django 3.2.5 on 2021-07-15 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0005_auto_20210715_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='Galerias', verbose_name='Imagen de galeria')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('update', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('proyectoPertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portafolio.proyecto')),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galerias',
            },
        ),
    ]
