# Generated by Django 3.2.5 on 2021-07-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0006_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='nombre',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nombre de la imagen'),
        ),
    ]
