# Generated by Django 3.2.5 on 2021-07-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0007_galeria_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='descripcionTrabajo',
            field=models.TextField(blank=True, max_length=40000, null=True, verbose_name='Descripcion del protyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='contenido',
            field=models.TextField(max_length=400, verbose_name='Descripcion del protyecto'),
        ),
    ]
