# Generated by Django 3.2.5 on 2021-11-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0009_alter_proyecto_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='destacado',
            field=models.BooleanField(blank=True, null=True, verbose_name='mostrar en inicio'),
        ),
    ]
