# Generated by Django 3.2.9 on 2021-11-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0010_proyecto_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='Portafolio/banner', verbose_name='Imagen de 1600X300'),
        ),
    ]
