# Generated by Django 3.2.5 on 2021-07-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0003_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='contenido',
            field=models.TextField(max_length=1000, verbose_name='Descripcion el servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(upload_to='servicios', verbose_name='Imagen para mostar'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Nombre del servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='update',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de actualizacion'),
        ),
    ]
