# Generated by Django 3.2.5 on 2021-07-20 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0005_alter_servicio_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspesificacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Nombre del servicio')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('update', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'espesificacion',
                'verbose_name_plural': 'espesificaciones',
            },
        ),
        migrations.CreateModel(
            name='Espesificaciondetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=50, verbose_name='Nombre del servicio')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('update', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('espesificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.espesificacionservicio')),
            ],
            options={
                'verbose_name': 'espesificacion',
                'verbose_name_plural': 'espesificaciones',
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='servicioEspesificacion',
            field=models.ManyToManyField(to='Servicios.EspesificacionServicio'),
        ),
    ]
