# Generated by Django 3.2.5 on 2021-07-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0006_auto_20210720_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espesificaciondetalle',
            options={'verbose_name': 'espesificacion detalles', 'verbose_name_plural': 'espesificaciones detalles'},
        ),
        migrations.AlterModelOptions(
            name='espesificacionservicio',
            options={'verbose_name': 'espesificacion servicio', 'verbose_name_plural': 'espesificaciones de servicio'},
        ),
        migrations.AddField(
            model_name='espesificacionservicio',
            name='cajadetexto',
            field=models.BooleanField(null=True, verbose_name='Llevara caja e texto?'),
        ),
        migrations.AlterField(
            model_name='espesificaciondetalle',
            name='detalle',
            field=models.CharField(max_length=50, verbose_name='detalle'),
        ),
    ]
