# Generated by Django 3.2.5 on 2021-11-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0007_auto_20210720_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Nombre del bloque de servicios')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('update', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'espesificacion servicio',
                'verbose_name_plural': 'espesificaciones de servicio',
            },
        ),
    ]
