# Generated by Django 3.2.5 on 2021-11-14 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0008_bloqueservicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloqueservicio',
            options={'verbose_name': 'Bloque de servicios', 'verbose_name_plural': 'Bloques de servicios'},
        ),
        migrations.AddField(
            model_name='servicio',
            name='bloque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Servicios.bloqueservicio'),
        ),
    ]
