# Generated by Django 3.2.9 on 2021-11-17 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0009_auto_20211114_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50, verbose_name='Nombre del Area')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('update', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Bloque de servicios',
                'verbose_name_plural': 'Bloques de servicios',
            },
        ),
        migrations.AddField(
            model_name='bloqueservicio',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Servicios.areaservicio'),
        ),
    ]
