# Generated by Django 3.2.9 on 2021-11-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0010_auto_20211117_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaservicio',
            options={'verbose_name': 'Area de servicios', 'verbose_name_plural': 'Areas de servicios'},
        ),
    ]
