# Generated by Django 3.2.9 on 2021-11-17 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0011_alter_areaservicio_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=100, verbose_name='Detalle del area')),
                ('realisable', models.BooleanField(verbose_name='Se realiza el trabajo?')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('update', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.areaservicio')),
            ],
            options={
                'verbose_name': 'detalle del area',
                'verbose_name_plural': 'detalles de area',
            },
        ),
    ]
