# Generated by Django 3.2.9 on 2021-11-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0012_detallesarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesarea',
            name='realisable',
            field=models.BooleanField(null=True, verbose_name='Se realiza el trabajo?'),
        ),
    ]
